### ISSUE TITLE
Always throws index out of range!

### ISSUE THREAD

**Issue by benyu** [yob/pdfreader#1]
goroutine 1 [running]:
github.com/yob/pdfreader/fancy.(*SecReaderT).ReadByte(0x20825a000, 0x208258200, 0x0, 0x0)
    /Users/benyu/go/src/github.com/yob/pdfreader/fancy/fancy.go:125 +0x94
github.com/yob/pdfreader/ps.skipSpaces(0x2208239a08, 0x20825a000, 0x0)
    /Users/benyu/go/src/github.com/yob/pdfreader/ps/ps.go:41 +0x2e
github.com/yob/pdfreader/ps.Token(0x2208239a08, 0x20825a000, 0x0, 0x0, 0x0, 0x0)
    /Users/benyu/go/src/github.com/yob/pdfreader/ps/ps.go:117 +0x4d
github.com/yob/pdfreader/pdfread.xrefRead(0x2208239a08, 0x20825a000, 0xffffffffffffffff, 0x20825a000)
    /Users/benyu/go/src/github.com/yob/pdfreader/pdfread/pdfread.go:189 +0x12f
github.com/yob/pdfreader/pdfread.Load(0x7fff5fbff9e7, 0x1f, 0xa1fcc)
    /Users/benyu/go/src/github.com/yob/pdfreader/pdfread/pdfread.go:439 +0x122
main.main()
    /Users/benyu/go/src/github.com/yob/pdfreader/pdtest/pdtest.go:15 +0x51

**Comment by divan** [comment]
I also have a PDF which triggers this bug.
@benyu did you find a solution?

**Comment by benyu** [comment]
No, so i choose another solution: 
https://github.com/coolwanglu/pdf2htmlEX

**Comment by gcobr** [comment]
Same problem. No solution.
